#!/bin/bash

echo "Installing package."
echo "Making build files."

cmake -S . -B build
cmake --build build

echo "Installing executables."

sudo cp build/lsa /usr/local/bin/lsa
sudo cp build/lsall /usr/local/bin/lsa

echo "Installing man files"

cp src/lsall.1 /usr/share/man/man1

echo "Installation done."

